# Generated by Django 4.1.1 on 2022-10-05 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='movies', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'mp4'])])),
            ],
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='core_movie_name_131056_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['country'], name='core_movie_country_d7be21_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['age'], name='core_movie_age_b4e517_idx'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='file',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.FileField(default=django.utils.timezone.now, upload_to='covers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
       
        migrations.AddField(
            model_name='moviefile',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie'),
        ),
    ]
